{% set name = "graphysio" %}
{% set version = "2024.11.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e27b5637494d0f4b7be882e412f8a2449b56ccc21f5aaad1880b03f8bdaf87d3

build:
  noarch: python
  entry_points:
    - graphysio = graphysio.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - poetry >=0.12
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - pandas >=2,<3
    - pathvalidate >=3,<4
    - pint >=0.24,<1
    - pyqt >=5,<7
    - pyqtgraph >=0.13,<1
    - scipy >=1.13,<2
    - numexpr >=2.9,<3
    - physiocurve >=2024.9.24,<2025
    - pyarrow >=14
    - pyedflib >=0.1.37,<0.2
    - pebble >=5.0.7,<6
    - dwclib >=2024.9.17,<2025

test:
  imports:
    - graphysio
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jaj42/GraPhysio
  summary: GUI time series visualizer for biometric data
  description: |
    GraPhysio is a graphical time series visualizer created for biometric data
    signals from ICU patient monitors. It is however not limited to this. It
    can handle low frequency and high frequency data as well as aggregating and
    synchronizing signals from different sources. GraPhysio supports basic
    mathematical operations and filters and can help selecting and exporting
    time periods. GraPhysio can read data from CSV, Parquet and EDF files and
    can write CSV, Parquet, EDF and Matlab files.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/jaj42/GraPhysio

extra:
  recipe-maintainers:
    - jaj42
